site_name: Flockwave protocol specification

repo_name: Git repository
repo_url: https://git.collmot.com/collmot/flockwave-spec

theme: readthedocs

docs_dir: doc/protocol
site_dir: build/doc

pages:
  - Home: 'index.md'
  - Synopsis and conventions: 'synopsis.md'
  - Definitions: 'definitions.md'
  - General protocol description: 'general.md'
  - UAV devices and channels: 'devices.md'
  - Known message types:
    - 'ACK - Acknowledgment messages': 'messages/ack.md'
    - 'CLK - Clocks and timers': 'messages/clk.md'
    - 'CMD - Direct command execution': 'messages/cmd.md'
    - 'CONN - Connections': 'messages/conn.md'
    - 'DEV - Devices and channels': 'messages/dev.md'
    - 'SYS - System information': 'messages/sys.md'
    - 'UAV - UAV-related messages': 'messages/uav.md'
  - Data types used in messages: 'types.md'
  - Transport layer: 'transport.md'
  - Security issues: 'security.md'
  - FAQ: 'faq.md'

markdown_extensions:
  - markdown.extensions.def_list:
  - markdown.extensions.footnotes:

