[tool.poetry]
name = "flockwave-spec"
version = "1.51.0"
description = "JSON-Schema specification of the Flockwave protocol"
authors = ["Tamas Nepusz <tamas@collmot.com>"]
packages = [
    { include = "flockwave", from = "src" }
]
include = ["src/flockwave/spec/*.json"]

[tool.poetry.dependencies]
python = "^3.7"
click = {version = "^8.0.0", optional = true}
jsonschema = {version = "^3.2.0", optional = true}
jsonpointer = "^2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
coverage = {extras = ["toml"], version = "^5.2"}
pytest-cov = "^2.10.0"

[tool.poetry.extras]
cli = ["click", "jsonschema"]

[[tool.poetry.source]]
name = "collmot"
url = "https://pypi.collmot.com/simple/"

[tool.coverage.paths]
source = ["src"]

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
show_missing = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
